branches:
  only:
    - gh-pages
    - /.*/
language: ruby
rvm:
- 2.1.1
sudo: false
cache: bundler
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - secure: "DJ9EuDuGm2QZDfAFeTET+OUd3tQJ1myhRLTdFnWLtVBd9tAW+XD+ZUOnU7E3W2ujV/WJ/4sIrf2RamOzAJhROaLW4dhf7mswkkaiYAbylG2Ma/xHlKW80cnT1TVe/eCBUvicRIFtpeU2JBYg9upKSApmoROrLd4QOxntz2xKGKQ="
bundler_args: "--with test"
before_install:
- nvm install # Install node from .nvmrc
- nvm use # Use node version from .nvmrc
- npm install
- npm install -g phantomjs
- npm install -g surge
script:
- bundle exec rake htmlproof
- bundle exec rake test
after_success:
# If this is a pull request, stage it and stick a message in the PR comments
- test $TRAVIS_PULL_REQUEST && bundle exec stage && bundle exec rake tag_pull_request
# If we're on gh-pages and not a PR, deploy to production
- test $TRAVIS_BRANCH == "gh-pages" && test $TRAVIS_PULL_REQUEST == "false" && surge --project ./public --domain https://dev.socrata.com
notifications:
  slack:
    secure: P6Mce/govM2MEy8RCTZHhG2Mg+2Bmh6d84GXt3lKUGPSv9u5Xww0Ld7K+rh7C5/qxSqQIfCY6m2TbtQbz1IpfuSWpvA9QwANYGr/gyzXFvd6pV8gRValb+juokxmNwjL5JmP8TdaX8IKrUgx9eb26j+0dEUbGLZR/kZfT0CX048=
