# Jekyll Config
destination: public
exclude: 
- public
- Rakefile
- Gemfile
- Gemfile.lock
- .rvmrc, 
- sample-code
- vendor
- README.md
- node_modules
- _tests
- package.json
- bin

permalink: pretty

# Template Config
splash: false
splash_homepage: false

ga_tracking_code: "UA-9046230-3"

subsite: dev
title: SODA Developers
icon: fa fa-code
github_repo: https://github.com/socrata/dev.socrata.com
contribute: /contributing.html

dataset_limit: 50000

# Setup for RSS feeds
name: 'Socrata Developer Portal'
description: 'Updates, examples, and significant changes to http://dev.socrata.com'
url: 'https://dev.socrata.com'
author: 
  name: 'Socrata Developer Program'
  uri: 'https://dev.socrata.com'

# JS Configuration Flags
flags:
  show_migration: true
  peeper:
    img: '/img/peeper.png'
    link: '/support.html'
    delay: 4000

# Path is relative to /common/js/common.js
custom_js:
- /js/main.js
- /js/snuffleupadata.js
- /js/peeper.js
- /js/github.js
- /common/js/lib/socrata-status.js
- /common/js/lib/ga-tracking.js

gems:
- jekyll-redirect-from
- jekyll-mentions
- jekyll-feed

# Offline mode plugin
offline: false
