destination: public
exclude: [Makefile, Gemfile, Gemfile.lock, .rvmrc, public, sample-code]
# permalink: pretty
splash: false
splash_homepage: false

ga_tracking_code: "UA-9046230-3"

subsite: dev
title: SODA Developers
icon: fa fa-code
github_repo: https://github.com/socrata/dev.socrata.com
contribute: /contributing.html

flags:
  show_migration: true

local_js:
  - //cdnjs.cloudflare.com/ajax/libs/mustache.js/0.8.1/mustache.min.js
  - /common/js/purl.js
  - /common/js/try.js
  - /js/snuffleupadata.js
  - /js/github.js
  - /js/external-link.js

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions

# Offline mode plugin
offline: false
